### ISSUE TITLE
Navigate to another dashboard from image click

### ISSUE THREAD

**Issue by almapab** [VolkovLabs/grafana-image-panel#19]
It would be very useful if there were an option to associate a url link with the image in order to navigate to the url when the image is clicked. My intention is create a dashboard menu based on images rather than text.

**Comment by mikhailredis** [comment]
@almapab, version 2.3.0 released and submitted to Grafana for the review.
Meanwhile, you can install it and try using the custom URL: https://github.com/VolkovLabs/grafana-image-panel/releases/download/v2.3.0/volkovlabs-image-panel-2.3.0.zip

Be aware, Grafana has an issue with clicking on images, I hope it will be resolved soon: https://github.com/grafana/grafana/issues/41445

**Comment by almapab** [comment]
Perfect, thanks for your work.

> @almapab, thank you for submitting the issue. I can add URL in the panel's options similar to links for other Grafana panels, is it what you are looking for?
> 
> Do you expect to use variables in the URL? I have to test to see how it works.

Perfect, thanks for your work.

**Comment by mikhailredis** [comment]
@almapab, version 2.3.0 was added to the Grafana repository (https://grafana.com/grafana/plugins/volkovlabs-image-panel/), but it has the issue I mentioned before.

The new version 2.3.1 with proposed workaround was released and submitted to the repository: https://github.com/VolkovLabs/grafana-image-panel/releases/tag/v2.3.1

Please let me know if there is anything else.
