### ISSUE TITLE
Display base64 Image from InfluxDB

### ISSUE THREAD

**Issue by gercorri** [VolkovLabs/grafana-image-panel#6]
Hi, I came across your plugin for Grafana and was hoping it would solve a problem where I have been having trying to display a base64 heatmap image from a camera which is stored in InfluxDB.

![image](https://user-images.githubusercontent.com/9036365/122638297-4648cc00-d0eb-11eb-8b7d-315dda3eed31.png)

As you can see from the attached image I have created two panels, one with your image-panel plugin and one with a table. I have the same flux query in both:

from(bucket: "cam_data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cam_data")
  |> filter(fn: (r) => r["_field"] == "heatmap")
  |> keep(columns: ["_value"])
  |> yield(name: "last")
  
This query returns the value from the heatmap field in InfluxDB which contains the base64 encode image. The image is being displayed properly in the table but not in the panel using your plugin.
  
The data returned as _value is in the format data:image/jpg;base64,/9j/4AAQSkZJ.....

Can you advise if there is something else I need to do with the plugin or how I can get it to display the image?

Thanks,
Gerard.

**Comment by mikhailredis** [comment]
Hello Gerard,

  Thank you for opening the issue.
  The plugin does not expect the `data:image/jpg;base64,XXX` in the results, I have tested it with base64 results only.
  I will update the plugin and will get back to you shortly.

**Comment by mikhailredis** [comment]
@gercorri Fix was merged. What Grafana version do you use?
I am planning to upgrade the plugin for v8, which is incompatible with v7, and submit a new version for review.

**Comment by gercorri** [comment]
Hi @mikhailredis, thanks for the quick response on this. We are currently using 7.3.0, we have made some customisations so may be a problem for us to upgrade to 8, in the short term.

**Comment by mikhailredis** [comment]
@gercorri, I did releases for Grafana 7 and Grafana 8: https://github.com/VolkovLabs/grafana-image-panel/releases.

You can install the latest version 1.1.0 for Grafana 7:
- by downloading and unpacking: https://github.com/VolkovLabs/grafana-image-panel/releases/download/v1.1.0/volkovlabs-image-panel-1.1.0.zip
- `grafana-cli` https://grafana.com/docs/grafana/latest/administration/cli/ using the download link.

Let me know if the plugin works or you have any questions.

**Comment by gercorri** [comment]
Hi @mikhailredis, I tested in Grafana 7 with InfluxDB 2.0 as the source and it works well. Many thanks for the new version.

![image](https://user-images.githubusercontent.com/9036365/122814861-a9458900-d2cc-11eb-83e6-82bd673ae3fe.png)
